### ISSUE TITLE
It's not detecting my images and mask file

### ISSUE THREAD

**Issue by pkmnsandy** [Jonathunky/rembg-trainer#3]
Why I am getting these errors despite having all my images and their corresponding binary files in their respective folders?

Learning the dataset itself...

Training Images Found:
[]
Number of Images: 0
Training Masks Found:
[]
Number of Masks: 0
Traceback (most recent call last):
  File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 578, in <module>
    main()
  File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 568, in main
    create_and_train(
  File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 547, in create_and_train
    dataloader = get_dataloader(
                 ^^^^^^^^^^^^^^^
  File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 382, in get_dataloader
    dataloader = DataLoader(
                 ^^^^^^^^^^^
  File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 144, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by shuaimoumou** [comment]
> Why I am getting these errors despite having all my images and their corresponding binary files in their respective folders?
> 
> Learning the dataset itself...
> 
> Training Images Found: [] Number of Images: 0 Training Masks Found: [] Number of Masks: 0 Traceback (most recent call last): File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 578, in main() File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 568, in main create_and_train( File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 547, in create_and_train dataloader = get_dataloader( ^^^^^^^^^^^^^^^ File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 382, in get_dataloader dataloader = DataLoader( ^^^^^^^^^^^ File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 351, in **init** sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 144, in **init** raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}") ValueError: num_samples should be a positive integer value, but got num_samples=0

Your mistake was caused by the absence of 0 images and masks

**Comment by pkmnsandy** [comment]
Thank you for the replt

> > Why I am getting these errors despite having all my images and their corresponding binary files in their respective folders?
> > Learning the dataset itself...
> > Training Images Found: [] Number of Images: 0 Training Masks Found: [] Number of Masks: 0 Traceback (most recent call last): File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 578, in main() File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 568, in main create_and_train( File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 547, in create_and_train dataloader = get_dataloader( ^^^^^^^^^^^^^^^ File "/Users/pkmnsandy/rembg-trainer/u2net_train.py", line 382, in get_dataloader dataloader = DataLoader( ^^^^^^^^^^^ File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 351, in **init** sampler = RandomSampler(dataset, generator=generator) # type: ignore[arg-type] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/pkmnsandy/anaconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 144, in **init** raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}") ValueError: num_samples should be a positive integer value, but got num_samples=0
> 
> Your mistake was caused by the absence of 0 images and masks

Thank you for the reply. What do you mean by the absence of 0 images and masks? I have all the original images (saved in images folder) and their corresponding mask images (saved in masks folder), with the same file names and file extension (i.e. .jpg). Still I got this error.

**Comment by arasad28** [comment]
I got the same issue, after rename the images jpg to png. it worked for me
all the image should be in png extension

**Comment by shuaimoumou** [comment]
If you haven't solved this problem yet, pay attention to the case of the suffix in the image file and try debugging to the load_dataset function to investigate.

**Comment by pkmnsandy** [comment]
> I got the same issue, after rename the images jpg to png. it worked for me all the image should be in png extension

Hey, I tried this suggestion and now it works for me :D
